use soroban_sdk::contracterror;

#[contracterror]
#[derive(Copy, Clone, Debug, Eq, PartialEq)]
pub enum ContractError {
    InsufficientFunds = 1,
    ActiveLoanExists = 2,
    StakeOverflow = 3,
    ZeroAddress = 4,
    DuplicateVouch = 5,
    NoActiveLoan = 6,
    ContractPaused = 7,
    LoanPastDeadline = 8,
    MinStakeNotMet = 13,
    LoanExceedsMaxAmount = 14,
    UnauthorizedCaller = 16,
    InvalidAmount = 17,
    InvalidStateTransition = 18,
    AlreadyInitialized = 19,
    VouchCooldownActive = 21,
    VoucherNotWhitelisted = 23,
    Blacklisted = 24,
    TimelockNotFound = 25,
    TimelockNotReady = 26,
    TimelockExpired = 27,
    VoucherNotFound = 29,
    InvalidToken = 30,
    AlreadyVoted = 31,
    SlashVoteNotFound = 32,
    SlashAlreadyExecuted = 33,
    QuorumNotMet = 34,
    AlreadyRepaid = 35,
    // #684: Admin Delegation
    PermissionNotDelegated = 36,
    // #685: Admin Veto Power
    ProposalVetoed = 37,
    /// Voucher and borrower must be different addresses.
    SelfVouchNotAllowed = 38,
    InvalidBps = 39,
    DuplicateToken = 40,
    LoanNotCancellable = 41,
    CancellationWindowExpired = 42,
    LoanTooLarge = 43,
    LargeLoanNotApproved = 45,
    LargeLoanAlreadyExecuted = 47,
    CircularVouchDetected = 48,
    VouchConflictDetected = 51,
    VouchTooYoungToWithdraw = 52,
    StakeLimitExceeded = 53,
    FunctionPaused = 54,
    InvalidAdminThreshold = 55,
    DisputeWindowExpired = 56,
    DisputeNotFound = 57,
    DisputeAlreadyResolved = 58,
}
